<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregates\" />
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Events\" />
    <Folder Include="Factories\" />
    <Folder Include="Services\" />
    <Folder Include="Rules\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResearchAtlas.Domain.Abstractions\ResearchAtlas.Domain.Abstractions.csproj" />
    <ProjectReference Include="..\ResearchAtlas.Extensions\ResearchAtlas.Extensions.csproj" />
  </ItemGroup>

</Project>
